name: Run Python in Docker

on:
  push:
    branches: ["main"]

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build image
      run: docker build -t myapp .

    - name: Run container
      run: docker run myapp
